[network]
name = "devnet"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "twice particular affair smile push picture miss direct toss property leave nose window party shrug lizard glass"
balance = 10_000_000_000_000

[accounts.wallet_1]
mnemonic = "sell invite acquire kitten bamboo drastic jelly vivid peace spawn twice guilt pave pen trash pretty park"
balance = 10_000_000_000_000

[accounts.wallet_2]
mnemonic = "hold excess usual excess ring elephant install account animal crude payment gift elevator budget fiber"
balance = 10_000_000_000_000

[accounts.wallet_3]
mnemonic = "cycle puppy glare enroll cost improve round trend wrist mushroom scorpion tower claim oppose clever"
balance = 10_000_000_000_000

[devnet]
disable_stacks_explorer = false
disable_stacks_api = false
stacks_node_events_observers = ["host.docker.internal:8002"]
bitcoin_node_username = "devnet"
bitcoin_node_password = "devnet"
miner_mnemonic = "twice particular affair smile push picture miss direct toss property leave nose window party shrug lizard glass"
miner_derivation_path = "m/44'/5757'/0'/0/0"
faucet_mnemonic = "shadow private easily thought say logic fault paddle word top book during ignore notable orange flight clock image wealth health"
faucet_derivation_path = "m/44'/5757'/0'/0/0"
orchestrator_port = 20445
bitcoin_node_p2p_port = 18444
bitcoin_node_rpc_port = 18443
stacks_node_p2p_port = 20444
stacks_node_rpc_port = 20443
stacks_api_port = 3999
stacks_api_events_port = 3700
bitcoin_explorer_port = 8001
stacks_explorer_port = 8000
epoch_2_0 = 100
epoch_2_05 = 100
epoch_2_1 = 101
epoch_2_2 = 102
epoch_2_3 = 103
epoch_2_4 = 104
epoch_2_5 = 105
pox_2_activation = 102
